# Project testDAO for DAOmocracy
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="testDAO"
ORG_DBA="testDAO token"
ORG_URL="https://daomocracy.github.io/testDAO/"
ORG_LOGO="https://raw.githubusercontent.com/DAOmocracy/testDAO/main/public/testDAO.png"
ORG_DESCRIPTION="DAO test for DAOmocracy."

[[DAO]]
DAO_ASSET="testDAO"
DAO_ADMIN=[
"GC6QKE63CSE4XATU6BY7COP3XBMKD5LUAAE3IF3LNR4VCH75XDQFXQGX",
"GD7375UUB266OHX5RQS7SGS37H3YX2P2VKZE332HDIKJSQDORIPJIA4W"
]
DAO_LOGO="https://raw.githubusercontent.com/DAOmocracy/testDAO/main/public/testDAO.png"

[[CURRENCIES]]
code="testDAO"
name="testDAO"
issuer="GCIKW6FLYZEPFZ6C2LSQCXQCUM3GB5ZOPFOHJVN25SPZZ4LXAEHVHKR3"
is_asset_anchored=false
display_decimals=7
desc="testDAO has no value, but will be used solely for testing purpose."
image="https://raw.githubusercontent.com/DAOmocracy/testDAO/main/public/testDAO.png"
conditions="testDAO has no value."
